### ISSUE TITLE
How to use it in es6?

### ISSUE THREAD

**Issue by hank2718** [anncwb/vite-plugin-svg-icons#1]
How to use it in es6?

**Comment by anncwb** [comment]
Can you describe your mistake in detail? Don't know what you mean

**Comment by hank2718** [comment]
Use js,not ts

**Comment by anncwb** [comment]
You did not provide more information. Can't help you

**Comment by anncwb** [comment]
This plugin has nothing to do with js and ts

**Comment by hank2718** [comment]
// vite.config.js

**Comment by hank2718** [comment]
```javascript
// vite.config.js
export default defineConfig({
  plugins: [
    vue(),
    viteSvgIcons({
      iconDirs: [path.resolve(process.cwd(), 'src/icons')],
      symbolId: 'icon-[dir]-[name]',
    }),
  ]
})
// main.js
import { createApp } from 'vue'
import App from '@/App.vue'
import 'vite-plugin-svg-icons/register'

![image](https://user-images.githubusercontent.com/7368299/111093139-24333100-8573-11eb-9321-54bc7b059d51.png)

**Comment by anncwb** [comment]
I tried your writing in the example and also in the window system, but this problem did not appear. Can you help write a github replication repository.

**Comment by anncwb** [comment]
Upgrade to 0.4.0 can be solved. You did not provide important information because you configured the base, so I have not reproduced it
