### ISSUE TITLE
SSR: Failed to load module: virtual:svg-icons-register

### ISSUE THREAD

**Issue by MewenLr** [anncwb/vite-plugin-svg-icons#11]
Hi, I got some trouble rendering icons using vite-plugin-svg-icons on a vue/vite project with ssr.

On development, it's returning : Error: failed to load module for ssr: virtual:svg-icons-register

This bug showed up after the release 0.6.0 I think

Here is a reproducible repo > https://github.com/MewenLr/vite-ssr-svgIcons-error

**Comment by anncwb** [comment]
Try v0.7.0

**Comment by MewenLr** [comment]
It's working now. thank you
