### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: (0 , _svgbaker2.default) is not a constructo

### ISSUE THREAD

**Issue by Ttou** [anncwb/vite-plugin-svg-icons#14]
vite-plugin-svg-icons： 1.0.2

![image](https://user-images.githubusercontent.com/4298437/127792047-945cebcf-9504-4053-ba81-330e79220552.png)

**Comment by anncwb** [comment]
Upgrade to 1.0.3

**Comment by Ttou** [comment]
fixed
