### ISSUE TITLE
vite+react svg配置不起作用  

### ISSUE THREAD

**Issue by guozhenqianga** [anncwb/vite-plugin-svg-icons#29]
vite 2.6.13  vite-plugin-svg-icons@1.0.5
配置
![1637747947(1)](https://user-images.githubusercontent.com/23112360/143216518-5ef4dd0a-1518-4c41-9f6c-32ddd4390637.jpg)

组件
![1637747978(1)](https://user-images.githubusercontent.com/23112360/143216632-c9658930-5184-4035-a22c-9ed75a69d801.jpg)

使用
![1637748035(1)](https://user-images.githubusercontent.com/23112360/143216801-0c153c89-d266-4532-afa8-a13bf1a7209e.jpg)

icon位置
![1637748069(1)](https://user-images.githubusercontent.com/23112360/143217659-97e354cd-da4d-4851-891d-d84ff1671a1f.jpg)

不起作用显示不出来

**Comment by Spencer17x** [comment]
我试了也不行，你怎么close了？是改了什么东西之后可以了吗？
