### ISSUE TITLE
如果`svgoOptions`配置成false会怎么样?

### ISSUE THREAD

**Issue by VXiaoXin** [anncwb/vite-plugin-svg-icons#3]
我试了一下，貌似没有什么其他反应。因为VbenAdmin中该值被配置成了isBuild。所以`svgoOptions`配置成false会怎么样的?

**Comment by anncwb** [comment]
你可以看看这个https://github.com/svg/svgo，为true就是svgo默认的压缩，也可以自己配置svgo options
