### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by ugrupp** [anncwb/vite-plugin-svg-icons#4]
Hi, first of all, thanks for the plugin!

Unfortunately, in dev mode I'm getting a CORS error for `import "vite-plugin-svg-icons/register";`:

```Access to script at 'http://craft-starter-2021.nitro:2170/@id/vite-plugin-svg-icons/register' from origin 'http://craft-starter- 2021.nitro' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

I'm using vite with a traditional CMS, so vite only serves as an asset server on a different port than the CMS site. This is not a problem with vite since it can be configured to allow all origins via https://vitejs.dev/config/#server-cors.

Perhaps you could add such a setting to this plugin, too - or use the `server.cors` setting from the vite config if that makes sense?

**Comment by anncwb** [comment]
Have you tried configuring `server.cors:true` in vite.config.ts

https://vitejs.dev/config/#server-cors

**Comment by ugrupp** [comment]
Sort of, it's enabled by default & I didn't disable it.

**Comment by anncwb** [comment]
I don’t know the reason for it for the time being, because I haven’t appeared before, so I may need to investigate

**Comment by anncwb** [comment]
You can try in vite.config.js
 
```
 configureServer: ({ app }) => {
    app.use(cors({ origin: '*' }));
  },
```

**Comment by ugrupp** [comment]
Hmm isn't that a plugin specific hook? Wouldn't you have to include that inside the plugin?

I did a little digging, perhaps adding a CORS plugin setting and including it [here](https://github.com/anncwb/vite-plugin-svg-icons/blob/main/src/index.ts#L98) would do the trick?

**Comment by chaosprint** [comment]
> Hmm isn't that a plugin specific hook? Wouldn't you have to include that inside the plugin?
> 
> I did a little digging, perhaps adding a CORS plugin setting and including it [here](https://github.com/anncwb/vite-plugin-svg-icons/blob/main/src/index.ts#L98) would do the trick?

Would you like to try this?

https://github.com/chaosprint/vite-plugin-cross-origin-isolation

**Comment by yaron-shamul** [comment]
can you please share the solution that caused you to close this issue?
