### ISSUE TITLE
SSR Cannot find module 'vite-plugin-svg-icons/register'

### ISSUE THREAD

**Issue by jy0529** [anncwb/vite-plugin-svg-icons#7]
![image](https://user-images.githubusercontent.com/12868934/117950788-22ed6d00-b346-11eb-91ed-f4f33c64ac10.png)

vite-plugin-svg-icons version: ^0.5.0

 main.js
```javascript
// svg
import 'vite-plugin-svg-icons/register';
```

vite.config.js
```javascript
plugins: [
        createVuePlugin({ jsx: true }),
        viteSvgIcons({
            iconDirs: [path.resolve(process.cwd(), 'src/assets/editor-svg')],
            symbolId: '[name]',
            svgoOptions: {
                plugins: ['removeDoctype', 'removeComments', 'removeMetadata', 'removeTitle', 'removeDesc'],
            },
        }),
    ],
```

dist/entry-server.js
```javascript
require("vite-plugin-svg-icons/dist/index");
```
You can use https://github.com/vitejs/vite/tree/main/packages/playground/ssr-vue to reproduce.

**Comment by MewenLr** [comment]
@jy0529
The error seems to come from the import path given in the doc. Try :

import 'vite-plugin-svg-icons/register.d'

with '.d' at the end and it should work just fine

**Comment by anncwb** [comment]
0.6.0 has been fixed

**Comment by anncwb** [comment]
Upgrade to 0.6.1, then change `import'vite-plugin-svg-icons/register` to `virtual:svg-icons-register`
