### ISSUE TITLE
can not use svg with linearGradient

### ISSUE THREAD

**Issue by yangmi0829** [anncwb/vite-plugin-svg-icons#8]
want
svgDom.style.display = 'none' => svgDom.style.position = 'absolute'

**Comment by anncwb** [comment]
Can you give a reproduction example or specific information?

**Comment by yangmi0829** [comment]
> Can you give a reproduction example or specific information?

i fork and push request。
if   "svgDom.style.display = 'none'",
then, the svg look strange

**Comment by anncwb** [comment]
try 0.6.2
